nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
codigo_seccion = input("Ingrese su Codigo-seccion: ")
sede = input("Ingrese su sede: ")

print("\n Datos ingresados:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Codigo-seccion:", codigo_seccion)
print("Sede:", sede)
